---
title: "Projects"
---

## The Legislative Agenda Initiative in Latin America 

Representative democracy is in crisis and the principal instrument of direct democracy – the referendum – is often considered a blunt and risky instrument in an era of rising populism and misinformation. The legislative agenda initiative is a surprisingly neglected democratic tool that operates at the intersection between direct and representative democracy by allowing individuals,  following a signature gathering exercise, to request Parliament to legislate. It thereby offers a channel for direct citizen participation mediated by representative institutions. Appropriately configured, it could lead to increased policy responsiveness to the preferences of the citizenry. The instrument has diffused rapidly in recent decades, yet little is known about it. Building on earlier work on the diffusion of this instrument in Europe, this BA/Leverhulme funded project maps the features and practice of the LAI across Latin America.

This website presents data collected as part of the aforementioned project, this includes the existence of, and regulation relating to, different instruments of direct democracy in Latin America  including the legislative agenda initiative and the practice relating to the latter instrument.  


